server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/routines {
        proxy_pass http://routine-service:8080;
    }
    location /api/products {
        proxy_pass http://product-drop-service:8080;
    }
    location /api/alerts {
        proxy_pass http://notification-service:8080;
    }
    location /notificationHub {
        proxy_pass http://notification-service:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
